-- Wallet schema. Applied on every boot from db.js; every statement is
-- IF NOT EXISTS so that re-running it is a no-op.
--
-- SQLite has no date and no boolean type. Dates are TEXT in 'YYYY-MM-DD',
-- timestamps are ISO-8601 strings, booleans are INTEGER 0/1.
--
-- ALL DATES ARE LOCAL DATES WITH NO TIMEZONE CONVERSION. This is a personal
-- single-user app and the simplification is deliberate — writing it here makes
-- it a decision rather than an accident.
--
-- Money is amount_cents, an INTEGER, everywhere. 15,00 EUR is 1500. There is no
-- float arithmetic on money anywhere in this app, because 0.1 + 0.2 is not 0.3
-- and totals in floats cannot be reconciled months later.

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS categories (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name    TEXT NOT NULL,
  icon    TEXT,                      -- an emoji, e.g. '🛒'
  UNIQUE (user_id, name)
);

-- One row per thing that WILL happen. total_count IS NULL means a subscription
-- that never ends; total_count = N means a loan of N instalments. A loan is not
-- a separate concept, it is a schedule with a finite instalment count.
CREATE TABLE IF NOT EXISTS schedules (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name         TEXT    NOT NULL,
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  category_id  INTEGER REFERENCES categories(id),
  day_of_month INTEGER NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
  starts_on    TEXT    NOT NULL,     -- YYYY-MM-DD
  total_count  INTEGER,              -- NULL = subscription; N = loan of N instalments
  paid_count   INTEGER NOT NULL DEFAULT 0,
  active       INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT    NOT NULL DEFAULT (datetime('now')),
  CHECK (total_count IS NULL OR total_count > 0),
  CHECK (paid_count >= 0)
);

-- One row per thing that HAS happened. schedule_id is set when the row was
-- generated by paying an instalment.
CREATE TABLE IF NOT EXISTS transactions (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  category_id  INTEGER REFERENCES categories(id),
  spent_on     TEXT    NOT NULL,     -- YYYY-MM-DD
  note         TEXT,
  schedule_id  INTEGER REFERENCES schedules(id),  -- set when auto-generated
  created_at   TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_tx_user_date ON transactions (user_id, spent_on);
CREATE INDEX IF NOT EXISTS idx_sched_user   ON schedules (user_id, active);

-- One row per user, at most. Monthly income (spec §3, D-021): a single figure
-- that applies to every month. What remains is computed on read and never
-- stored, for the same reason next_due is not — a stored balance is wrong the
-- moment the next expense is added.
CREATE TABLE IF NOT EXISTS settings (
  user_id              INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  monthly_income_cents INTEGER NOT NULL DEFAULT 0 CHECK (monthly_income_cents >= 0)
);

-- AI draft quotas (D-034). Counters only: period, scope, user, count. No text.
-- period is 'YYYY-MM-DD' for daily scopes and 'YYYY-MM-DDTHH:MM' for the
-- minute scope; user_id 0 is the global counter, so there is no foreign key.
-- Rows older than two days are pruned on every reservation.
CREATE TABLE IF NOT EXISTS ai_quota (
  period  TEXT    NOT NULL,
  scope   TEXT    NOT NULL CHECK (scope IN ('global-day', 'user-day', 'user-minute')),
  user_id INTEGER NOT NULL,
  count   INTEGER NOT NULL DEFAULT 0 CHECK (count >= 0),
  PRIMARY KEY (period, scope, user_id)
);

-- Keyed saves (D-035). One row per successful keyed POST /api/transactions.
-- transaction_id deliberately has NO foreign key: when the expense is deleted
-- the row stays as a tombstone, so a late retry of the same key answers 409
-- instead of silently recreating the expense. Kept for the life of the account.
CREATE TABLE IF NOT EXISTS transaction_requests (
  user_id        INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  operation_key  TEXT    NOT NULL,
  payload_hash   TEXT    NOT NULL,
  transaction_id INTEGER NOT NULL,
  response_json  TEXT    NOT NULL,
  created_at     TEXT    NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (user_id, operation_key)
);
